services:
  manejador:
    build:
      context: ./manejador
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./manejador:/app

  postores:
    build:
      context: ./postores
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./postores:/app
